project:
  type: website
  resources: 
        - files/

website:
  title: "John Tan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
      - href: more.qmd
        text: More
  page-footer: 
    right: "&copy; 2025, John Sebastian Tan"
  
format:
  html:
    theme:
      - sandstone
      - styles.scss
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto